# Generated by Django 5.2.15 on 2026-07-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicterm',
            options={'ordering': ['-year', 'season']},
        ),
        migrations.RemoveConstraint(
            model_name='academicterm',
            name='unique_academic_term_name_per_season_year',
        ),
        migrations.RemoveField(
            model_name='academicterm',
            name='name',
        ),
        migrations.AddConstraint(
            model_name='academicterm',
            constraint=models.UniqueConstraint(fields=('season', 'year'), name='unique_academic_term_season_year'),
        ),
    ]
