# Generated by Django 5.2.15 on 2026-07-07 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_academicterm_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradecomponent',
            options={'ordering': ['course', 'name']},
        ),
        migrations.RemoveField(
            model_name='gradecomponent',
            name='category',
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='gradecomponent',
            name='name',
            field=models.CharField(choices=[('homework', 'Homework'), ('quiz', 'Quiz'), ('lab', 'Lab'), ('midterm', 'Midterm'), ('final', 'Final'), ('participation', 'Participation'), ('project', 'Project'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
