# Generated by Django 5.2.15 on 2026-07-07 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_gradecomponent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradeitem',
            options={'ordering': ['component', 'id']},
        ),
        migrations.RemoveField(
            model_name='gradeitem',
            name='due_date',
        ),
    ]
